version: '3.8'

services:
  app:
    build: .
    container_name: mutual-fund-portfolio-app
    ports:
      - "5000:5000"
    depends_on:
      - mysql-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/mutualfundpoc
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  mysql-container:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mutualfundpoc
    ports:
      - "3307:3306"